version: "1.0"
name: "nezora"
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: CHANGE_ME
      MARIADB_DATABASE: nezora
      MARIADB_USER: nezor
      MARIADB_PASSWORD: CHANGE_ME
    command: --max_allowed_packet=64000000      # Set max_allowed_packet to 64M (or any other value)
    restart: always
    ports:
      - "3306:3306"      
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
  backend:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "8001:3001"
    environment:
      GO_DB_HOST: db:3306
      MARIADB_DATABASE: nezora
      MARIADB_USER: nezor
      MARIADB_PASSWORD: CHANGE_ME
  web:
    depends_on:
      - backend
    build: ../frontend/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKENDHOST: 127.0.0.1:8001/api/v1
     
networks:
   dev-network:
        external: true
      
volumes:
    db_data:
    db_conf: